[package]

name = "html5ever"
version = "0.24.1"
authors = [ "The html5ever Project Developers" ]
license = "MIT / Apache-2.0"
repository = "https://github.com/servo/html5ever"
description = "High-performance browser-grade HTML5 parser"
documentation = "https://docs.rs/html5ever"
build = "build.rs"
categories = [ "parser-implementations", "web-programming" ]

[lib]
name = "html5ever"

doctest = true

[[test]]
name = "tree_builder"
harness = false

[[test]]
name = "tokenizer"
harness = false

[[test]]
name = "serializer"

[dependencies]
log = "0.4"
mac = "0.1"
markup5ever = { version = "0.9", path = "../markup5ever" }

[dev-dependencies]
serde_json = "1.0"
rustc-test = "0.3"
typed-arena = "1.3.0"
criterion = "0.3"

[build-dependencies]
quote = "1"
syn = { version = "1", features = ["extra-traits", "full", "fold"] }
proc-macro2 = "1"

[[bench]]
name = "html5ever"
harness = false
